### ISSUE TITLE
文件下载需要密码，在readme中没有看到相关说明，请告知

### ISSUE THREAD

**Issue by leolulu** [jbiaojerry/ebook-treasure-chest#1]
![image](https://github.com/user-attachments/assets/b76c294d-dc4d-4860-8da4-0c46a600ee08)
请问这个分享是免费的还是收费的，是需要收费才提供密码吗？

**Comment by goheye** [comment]
readme中没有看到密码，请问怎么获得

**Comment by solutine** [comment]
你好 下载密码从何处获得啊

**Comment by jbiaojerry** [comment]
抱歉，最近比较忙没有及时更新仓库，网盘链接现在更新了存储方式，建议大家先fork和watch，有新的更新及时同步给大家

**Comment by jbiaojerry** [comment]
文件链接已全部更新，无需密码
